[tool.poetry]
name = "juniorguru"
version = "0.0.0"
description = "Learn to code and get your first job in tech 🐣"
authors = ["Honza Javorek <mail@honzajavorek.cz>"]
license = "MIT"
readme = "README.md"
homepage = "https://junior.guru/"
repository = "https://github.com/honzajavorek/junior.guru/"

[tool.poetry.scripts]
jg = "juniorguru.cli:main"

[tool.poetry.dependencies]
python = "3.10.*"
jinja2 = "*"
gspread = "*"
oauth2client = "*"
arrow = "*"
markdown = "*"
flask = "*"
frozen-flask = "*"
pillow = "*"
peewee = "*"
strictyaml = "*"
langdetect = "*"
w3lib = "*"
lxml = "*"
cssselect = "*"
google-api-python-client = "*"
requests = "*"
itemloaders = "*"
fiobank = "*"
emoji = "*"
favicon = "*"
feedparser = "*"
py-cord = {version = "*", extras = ["speed"]}
gql = {extras = ["requests"], version = "*"}
mkdocs = "*"
markupsafe = "*"
ics = {version = "*", allow-prereleases = true}
pod2gen = "*"
Scrapy = "*"
python-slugify = "*"
playwright = "*"
click = "*"
extruct = "*"

[tool.poetry.dev-dependencies]
pytest = "*"
pync = "*"
flake8 = "*"
isort = "*"
sqlite-utils = "*"

[tool.pytest.ini_options]
python_files = "test_*.py *_test.py test.py"
testpaths = "."
addopts = "--ff --ignore=node_modules --ignore=__jobs_legacy__"
filterwarnings = ["ignore:the imp module is deprecated:DeprecationWarning"]

[tool.isort]
profile = "black"
lines_after_imports = 2
combine_as_imports = true
multi_line_output = 0
include_trailing_comma = false
extend_skip = ["__jobs_legacy__"]
known_local_folder = ["testing_utils"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
