[tool.poetry]
name = "juniorguru"
version = "0.0.0"
description = "Learn to code and get your first job in tech 🐣"
authors = ["Honza Javorek <mail@honzajavorek.cz>"]
license = "MIT"
readme = "README.md"
homepage = "https://junior.guru/"
repository = "https://github.com/honzajavorek/junior.guru/"

[tool.poetry.scripts]
jg = "juniorguru.cli:main"

[tool.poetry.dependencies]
python = "3.10.*"
jinja2 = "3.1.2"
gspread = "5.7.2"
oauth2client = "4.1.3"
arrow = "1.2.3"
markdown = "<3.4"  # mkdocs depend on <3.4
flask = "2.2.3"
frozen-flask = "0.18"
pillow = "9.4.0"
peewee = "3.16.0"
strictyaml = "1.7.3"
langdetect = "1.0.9"
w3lib = "2.1.1"
lxml = "4.9.2"
cssselect = "1.2.0"
google-api-python-client = "2.81.0"
requests = "2.28.2"
itemloaders = "1.0.6"
fiobank = "3.0.0"
emoji = "2.2.0"
favicon = "0.7.0"
feedparser = "6.0.10"
py-cord = {version = "2.4.0", extras = ["speed"]}
gql = {extras = ["requests"], version = "3.4.0"}
mkdocs = "1.4.2"
markupsafe = "2.1.2"
ics = {version = "0.8.0.dev0", allow-prereleases = true}
pod2gen = "1.0.3"
scrapy = "2.8.0"
python-slugify = "8.0.1"
playwright = "1.31.1"
click = "8.1.3"
extruct = "0.14.0"
mkdocs-gen-files = "0.4.0"
mkdocs-awesome-pages-plugin = "2.8.0"
juniorguru-chick = { git = "https://github.com/juniorguru/juniorguru-chick.git" }

[tool.poetry.dev-dependencies]
pytest = "7.2.2"
pync = "2.0.3"
flake8 = "6.0.0"
isort = "5.12.0"
sqlite-utils = "3.30"
ghp-import = "2.1.0"

[tool.pytest.ini_options]
python_files = "test_*.py *_test.py test.py"
testpaths = "."
norecursedirs = "node_modules __jobs_legacy__"
addopts = "--ff"
filterwarnings = [
    "ignore:the imp module is deprecated:DeprecationWarning",
    "ignore:_unicode_safe_getattr is deprecated:DeprecationWarning",
]

[tool.isort]
profile = "black"
lines_after_imports = 2
combine_as_imports = true
multi_line_output = 0
include_trailing_comma = false
extend_skip = ["__jobs_legacy__"]
known_local_folder = ["testing_utils"]

[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"
