version: 2.1


executors:
  python-js:
    docker:
      - image: circleci/python:3.8-node-browsers
    working_directory: ~/project


orbs:
  gh-pages: sugarshin/gh-pages@0.0.6


jobs:
  install:
    executor: python-js
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "poetry.lock" }}-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: poetry install && npm ci
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache/pypoetry/virtualenvs
            - ./node_modules
      - persist_to_workspace:
          root: "~"
          paths:
              - .cache/pypoetry/virtualenvs
              - project/node_modules
              - project

  lint-and-test:
    executor: python-js
    steps:
      - attach_workspace:
          at: "~"
      - run:
          name: Lint
          command: make lint
      - run:
          name: Test
          command: make test TESTOPTS=-v

  # needs $GOOGLE_SERVICE_ACCOUNT, $FIOBANK_API_KEY
  sync:
    executor: python-js
    steps:
      - attach_workspace:
          at: "~"
      - run: 'date +"%Y-%m-%d" > .today'  # saves today's date to a file so it can be used to expire cache
      - restore_cache:  # caches all HTTP communication of the scrapers for one day
          key: scrapy-{{ checksum ".today" }}
      - run:
          name: Sync data
          command: |
            export PROXIES_ENABLED=1
            export DISCORD_MUTATIONS_ENABLED=1
            make sync
      - save_cache:
          key: scrapy-{{ checksum ".today" }}
          paths:
            - .scrapy
      - persist_to_workspace:
          root: "~"
          paths:
              - project/juniorguru/data
              - project/juniorguru/images
      - run: tar -cvzf backup.tar.gz ./juniorguru/data
      - store_artifacts:
          path: ./backup.tar.gz  # all data gets backed up as a CI artifact

  build:
    executor: python-js
    steps:
      - run:
          name: Install fonts
          command: |
            echo "deb http://ftp.us.debian.org/debian buster main contrib" | sudo tee -a /etc/apt/sources.list
            echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
            sudo apt-get update
            while ! sudo apt-get install ttf-mscorefonts-installer
            do
              echo "Fonts installation failed! Retrying..."
            done
      - attach_workspace:
          at: "~"
      - run: make build
      - persist_to_workspace:
          root: "~"
          paths:
              - project/public
      - run: tar -cvzf public.tar.gz ./public
      - store_artifacts:
          path: ./public.tar.gz  # the generated HTML is made available for download (used in the deploy job)

  # needs $NOW_TOKEN, $NOW_ORG_ID, $NOW_PROJECT_ID
  deploy:
    executor: python-js
    steps:
      - attach_workspace:
          at: "~"
      - restore_cache:  # caches a dummy file .deploy which lets the subsequent code to recognize whether the git ref has been already deployed to Now or not
          key: deploy-{{ .Revision }}
      - run:
          name: Deploy
          command: |
            if [[ -f .deploy ]]; then
              echo "Looks like the build has been triggered by CircleCI (nightly, retries). Deploying with ZEIT Now CLI."
              sudo npm install --global --unsafe-perm now
              now --prod -t "$NOW_TOKEN"
            else
              echo "Looks like the build has been triggered by GitHub (there are no previous 'deploy' jobs for this commit). Skipping duplicate deploy with ZEIT Now CLI."
              echo "$CIRCLE_SHA1" > .deploy
            fi
      - add_ssh_keys:
          fingerprints:
            - "7b:0b:2c:9f:fb:18:db:35:8e:f4:3d:49:73:37:ee:c4"
      - run: mkdir -p ~/.ssh
      - run: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - gh-pages/deploy:
          build-dir: "public"
          git-email: "kure@junior.guru"
          git-user: "Kuře"
          ssh-fingerprints: "7b:0b:2c:9f:fb:18:db:35:8e:f4:3d:49:73:37:ee:c4"
          tmp-dir: ".deploy-tmp"
          workspace-root: "~/project"
      - save_cache:
          key: deploy-{{ .Revision }}
          paths:
            - .deploy

  # needs $SMTP_* (see readme)
  send:
    executor: python-js
    steps:
      - attach_workspace:
          at: "~"
      - run: |
          export LOG_LEVEL=debug
          export SMTP_ENABLED=1
          make send

  check-anchors:
    executor: python-js
    steps:
      - attach_workspace:
          at: "~"
      - run: make check-anchors

  check-links:
    executor: python-js
    steps:
      - attach_workspace:
          at: "~"
      - run: make check-links CHECKOPTS=--retry

  check-scrapers:
    executor: python-js
    steps:
      - attach_workspace:
          at: "~"
      - run: make check-scrapers

  check-performance:
    executor: python-js
    steps:
      - attach_workspace:
          at: "~"
      - run: make check-performance
      - run:
          command: tar -cvzf lighthouse.tar.gz ./lighthouse
          when: always
      - store_artifacts:
          path: ./lighthouse.tar.gz  # HTML and JSON reports from lighthouse


workflows:
  version: 2

  push:
    jobs:
      - install
      - lint-and-test:
          requires:
            - install
      - sync:
          requires:
            - install
      - build:
          requires:
            - sync
      - check-scrapers:
          requires:
            - sync
      - check-anchors:
          requires:
            - build
      - deploy:
          # This makes sure retries of 'main' builds still deploy,
          # even though they were not initiated by a GitHub push. Might
          # cause double deploy for builds initiated by GitHub push, but
          # the deploy job recognizes they're to be skipped.
          filters:
            branches:
              only:
                - main
          requires:
            - build
            - lint-and-test

  nightly:
    jobs:
      - install
      - sync:
          requires:
            - install
      - build:
          requires:
            - sync
      - check-scrapers:
          requires:
            - sync
      - check-links:
          requires:
            - build
      - deploy:
          requires:
            - build
      - check-performance:
          requires:
            - deploy
    triggers:
      - schedule:
          cron: "0 4 * * *"
          filters:
            branches:
              only:
                - main

  sending:
    jobs:
      - install
      - sync:
          requires:
            - install
      - send:
          requires:
            - sync
    triggers:
      - schedule:
          cron: "0 5 * * *"
          filters:
            branches:
              only:
                - main
