site_name: junior.guru
site_url: https://junior.guru/

nav:
  - Příručka: 'motivation/'
  - Práce: 'jobs/'
  - Klub: 'club/'  #'club.md'

markdown_extensions:
  - toc:
      permalink: '#'
      permalink_title: 'Odkaz přímo na tuto sekci'
  - tables
  - fenced_code
  - md_in_html
  - attr_list

theme:
  name: null
  custom_dir: theme/

plugins:
  - mkdocs-simple-hooks:
      hooks:
        on_page_markdown: 'juniorguru.mkdocs.hooks:on_page_markdown'
        on_env: 'juniorguru.mkdocs.hooks:on_env'
        on_page_context: 'juniorguru.mkdocs.hooks:on_page_context'

# Specifies which filters from juniorguru.lib.template_filters
# will be available in which Jinja2 templates.
#
# (Entirely custom config, which is processed in hooks.py)
template_filters:
  shared:
      - email_link
      - icon
  markdown:
      - sample
  theme: []

# Removed 'strict', because it gives warnings if linking non-existing targets. Once the Flask
# app is gone, 'strict' should return to be enabled.
#strict: true
