site_name: junior.guru
site_url: https://junior.guru/


nav:
  - Příručka:
      - Úvod: handbook/index.md
      - Motivace: motivation.md
      - Základy: learn.md
      - První praxe: handbook/practice.md
      - Psychika: handbook/mental-health.md
      - Git a GitHub: handbook/git.md
      - Hledání práce: handbook/candidate.md
      - Životopis: handbook/cv.md
      - LinkedIn: handbook/linkedin.md
  - Podcast: podcast.md
  - Práce: jobs/
  - Klub: club.md

  - Ceník: pricing.md
  - Pro přednášející: speaker.md

  - Témata:
      - topics/adventofcode.md
      - topics/codility.md
      - topics/codingbootcamppraha.md
      - topics/cs50.md
      - topics/csharp.md
      - topics/css.md
      - topics/czechitas.md
      - topics/data.md
      - topics/django.md
      - topics/djangogirls.md
      - topics/docker.md
      - topics/engeto.md
      - topics/flask.md
      - topics/git.md
      - topics/github.md
      - topics/greenfox.md
      - topics/interviews.md
      - topics/itnetwork.md
      - topics/java.md
      - topics/javascript.md
      - topics/laravel.md
      - topics/learn2code.md
      - topics/linux.md
      - topics/mentoring.md
      - topics/nette.md
      - topics/oop.md
      - topics/opensource.md
      - topics/php.md
      - topics/primakurzy.md
      - topics/pyladies.md
      - topics/python.md
      - topics/react.md
      - topics/reactgirls.md
      - topics/sdacademy.md
      - topics/sql.md
      - topics/step.md
      - topics/symfony.md
      - topics/testing.md
      - topics/udemy.md
      - topics/unicorn.md
      - topics/vsb.md
      - topics/vue.md
      - topics/wordpress.md

  - Pravidla:
      - Otázky a odpovědi: faq.md
      - Pravidla chování: coc.md
      - Obchodní podmínky: tos.md
      - Zásady ochrany osobních údajů: privacy.md
      - Čísla a grafy: open.md
      - Licence obsahu (CC BY-SA): https://creativecommons.org/licenses/by-sa/4.0/deed.cs

  - Přesměrování:
      - První praxe: practice.md
      - Hledání práce: candidate-handbook.md


markdown_extensions:
  - toc:
      toc_depth: '2-2'
      permalink: '#'
      permalink_title: Odkaz na tuto sekci
  - tables
  - fenced_code
  - attr_list


theme:
  name: null
  custom_dir: theme/


hooks:
  - hooks.py


# Removed 'strict', because it gives warnings if linking non-existing targets. Once the Flask
# app is gone, 'strict' should return to be enabled.
#strict: true
